- id: buildifier
  name: buildifier
  description: Format starlark code with buildifier
  entry: buildifier-wrapper.sh fix -mode=fix -lint=fix
  files: '^(.*/)?(.*\.bzl|.*\.sky|.*\.bazel|BUILD|.*\.BUILD|BUILD\..*\.oss|WORKSPACE|WORKSPACE\.bzlmod|WORKSPACE\.oss|WORKSPACE\..*\.oss)$'
  language: script
- id: buildifier-lint
  name: buildifier-lint
  description: Lint starlark code with buildifier
  entry: buildifier-wrapper.sh lint -mode=diff -lint=warn
  files: '^(.*/)?(.*\.bzl|.*\.sky|.*\.bazel|BUILD|.*\.BUILD|BUILD\..*\.oss|WORKSPACE|WORKSPACE\.bzlmod|WORKSPACE\.oss|WORKSPACE\..*\.oss)$'
  language: script
